# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.61885849 0.99604541 0.60085893]
  [0.78701259 0.34945403 0.710571  ]
  [0.60270317 0.00377837 0.26259899]]

 [[0.15422959 0.59437384 0.19126937]
  [0.10993424 0.92335956 0.79692722]
  [0.3706171  0.03399399 0.47996907]]

 [[0.52629737 0.35726461 0.84043251]
  [0.99912198 0.29111142 0.96168811]
  [0.89220521 0.56722663 0.19640544]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
import numpy as np
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
import numpy as np
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
import numpy as np
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x= (x-xmin)/(xmax-xmin)
print (x)

[[0.69502442 1.         0.25375136 0.62193452 0.32318016]
 [0.56418015 0.94776307 0.48577488 0.         0.1291259 ]
 [0.83829353 0.49418595 0.46194937 0.01640357 0.55967107]
 [0.91505259 0.68830626 0.99626535 0.5443655  0.67870915]
 [0.27360706 0.25689653 0.89042731 0.54756578 0.08394495]]


# 5.  How to find common values between two arrays?

In [9]:
import numpy as np
arr1 = np.array([5, 33, 45, 77, 99])
print("Array1: ",arr1)
arr2 = [33, 99, 41]
print("Array2: ",arr2)
print("Common values between two arrays:")
print(np.intersect1d(arr1, arr2))

Array1:  [ 5 33 45 77 99]
Array2:  [33, 99, 41]
Common values between two arrays:
[33 99]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [13]:
import numpy as np
x = np.random.randint(3,4,5)
y = np.random.randint(3,4,5)
equal = np.allclose(x,y)
print(equal)

True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [14]:
import numpy as np
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.4282526  0.05184217 0.69512139 0.10949434 0.54923379 0.37897842
 0.48201874 0.86966553 0.54862331 0.        ]


# 9. How to print all the values of an array?

In [23]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [26]:
import numpy as np
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y

array([[ 0.05770222, -0.17181283,  0.01983191, -0.52195949, -0.15109457,
        -0.06892492,  0.28333415,  0.41375381, -0.12814577,  0.26731549],
       [ 0.18067952,  0.46242872, -0.39337624, -0.25510228, -0.02793589,
        -0.22711296, -0.06312706,  0.35156594, -0.02605617, -0.00196358],
       [-0.47681736,  0.33295124, -0.05232046, -0.09596308, -0.13021965,
         0.20215679, -0.36870089,  0.38587333, -0.14440938,  0.34744948],
       [ 0.44571387, -0.09162269,  0.26454691, -0.29654333,  0.1585744 ,
        -0.39377045, -0.07183374,  0.08865159,  0.11569446, -0.21941102],
       [-0.08246565, -0.53082588,  0.03500027,  0.31008395, -0.30009073,
         0.15632387,  0.38643858,  0.27900551, -0.52683763,  0.27336771]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [27]:
import numpy as np
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)

[2. 5. 5. 3. 3. 2. 2. 4. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [28]:
import numpy as np
x = np.random.randint(0,10,(3,3))
y = np.random.randint(0,10,(3,3))
np.einsum("ij,ji->i", x, y)

array([94, 26, 89])

# 13.How to find the most frequent value in an array?

In [29]:
import numpy as np
x = np.random.randint(0,5,10)
print (x)
print('rank:', np.bincount(x).argmax())

[0 2 0 3 0 0 1 4 1 4]
rank: 0


# 14.How to get the n largest values of an array

In [30]:
import numpy as np
x = np.arange(1000)
np.random.shuffle(x)
n = 5
print (x[np.argpartition(-x,n)[:n]])

[998 997 999 996 995]


# 15.How to create a record array from a regular array?

In [38]:
import numpy as np
x = np.array([("Snehasish", 2.5, 3),
              ("Swain", 3.6, 2)])
y = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
y

rec.array([(b'Snehasis', 2.5, 3), (b'Swain', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])